---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service-for-httpd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    app: httpd-pod