pipeline {
    agent any
    }
    
    environment {
        ARM_CLIENT_ID     = credentials('jenkins-arm-client-id')
        ARM_CLIENT_SECRET = credentials('jenkins-arm-secret-secret')
    }

    stages{
        stage('Clean Workspace'){
            steps{
                cleanWs()
            }
        }
        
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/abhishek-bagde/jenkins-learn.git'
            }
        } 
        
        stage("Docker Build & Push"){
            steps{
                script {
                    sh 'docker build -t hellodocker:${BUILD_ID} ./app/Dockerfile'
                    sh 'docker login creadevsouthindia001.azurecr.io -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET'
                    sh 'docker push myacr.azurecr.io/myimage:${BUILD_ID}'
                    }
                }
            }
    }
    // post {
    //     always {
    //         // Remove the Docker image from the Jenkins agent
    //         sh 'docker rmi myimage:${BUILD_ID}'
    //     }